- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
      - ansible.builtin.debug:
          msg: "{{ lookup('hashi_vault', 'secret=secret/hello:value token=c975b780-d1be-8016-866b-01d0f9b688a5 url=http://myvault:8200') }}"
